In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
class Perceptron:
  def __init__(self, eta, epochs):
    self.weights = np.random.rand(3) * 1e-4
    print(f"self.weights: {self.weights}")
    self.eta = eta
    self.epochs = epochs

  def activationFucntion(self, inputs, weights):
    z = np.dot(inputs, weights)
    return np.where(z>0, 1,0)

  def fit(self, X,y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
    print(f"X_with_bias: {X_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch: {epoch}")
      y_hat = self.activationFucntion(X_with_bias, self.weights)
      print(f"predicted value: {y_hat}")
      error = self.y - y_hat
      print(f"errot: {error}")
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
      print(f"updated weights: {self.weights}")

  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
    return self.activationFucntion(X_with_bias, self.weights)





In [19]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,0,0,1]}

AND = pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [20]:
X =AND.drop('y', axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [21]:
y = AND.y
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [22]:
model = Perceptron(0.5, 10)
model.fit(X,y)

self.weights: [8.38959865e-05 7.36195000e-05 5.60859366e-05]
X_with_bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: [0 1 1 1]
errot: 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: [-0.4999161  -0.49992638  1.00005609]
for epoch: 1
predicted value: [0 0 0 0]
errot: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: [8.38959865e-05 7.36195000e-05 5.00056086e-01]
for epoch: 2
predicted value: [0 0 0 0]
errot: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: [5.00083896e-01 5.00073619e-01 5.60859366e-05]
for epoch: 3
predicted value: [0 1 1 1]
errot: 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: [8.38959865e-05 7.36195000e-05 1.00005609e+00]
for epoch: 4
predicted value: [0 0 0 0]
errot: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: [0.5000839  0.50007362 0.50005609]
for epoch: 5
predicted value: [0 1 1 1]
errot: 0    0
1   -1
2   -1
3    0
Name: 

In [ ]:
model.predict(X)